services:
  stress:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M